name: sws
favicon: null
layout_spectrum: 0.8952713934704661
typography_spectrum: 0.3639357886277139
title: Satsang with Swamiji
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.19851263449527323
  lightness: 0.32097762054763734
  saturation: 0.11509287473745644
  rhythmicContrast: 0.9789953920990229
purpose: []
